/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.club;

import controller.Controller;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.time.Month;
import javax.swing.JSpinner;
import models.Club;
import models.Season;
import java.util.*;
import javax.swing.JOptionPane;
import models.Match;

/**
 *
 * @author Ljubomir
 */
public class ClubInsertNewMatch extends javax.swing.JFrame {

    Club club;
    List<Season> seasons;
    List<Club> clubs;
    Controller k = Controller.getInstance();
    int[] minutes = {00, 15, 30, 45};

    /**
     * Creates new form ClubInsertNewMatch
     */
    public ClubInsertNewMatch(Club club) {
        initComponents();
        this.club = club;
        seasons = k.getAllSeasons();
        for (Season s : seasons) {
            jcbSeason.addItem(s);
        }
        clubs = k.getAllClubs();
        for (Club c : clubs) {
            if (c.getIdKlub() != club.getIdKlub()) {
                jcbGuest.addItem(c);
            }
        }
        txtHost.setText(club.getFullName());
        addListener();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGoBack1 = new javax.swing.JButton();
        welcomeMessage = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jcbSeason = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbGuest = new javax.swing.JComboBox<>();
        txtHost = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jcbYear = new javax.swing.JComboBox<>();
        jcbMonth = new javax.swing.JComboBox<>();
        jcbDay = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jcbHours = new javax.swing.JComboBox<>();
        jcbMinutes = new javax.swing.JComboBox<>();
        jbtnUpdateNew = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sport tickets shop | Insert new match");
        setResizable(false);

        btnGoBack1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGoBack1.setText("<");
        btnGoBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBack1ActionPerformed(evt);
            }
        });

        welcomeMessage.setEditable(false);
        welcomeMessage.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        welcomeMessage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        welcomeMessage.setText("Insert new match");
        welcomeMessage.setBorder(null);
        welcomeMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                welcomeMessageActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Season:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Host:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Guest:");

        txtHost.setEditable(false);
        txtHost.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Date:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Year");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Month");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Day");

        jcbYear.setPreferredSize(new java.awt.Dimension(100, 22));

        jcbDay.setPreferredSize(new java.awt.Dimension(70, 22));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Time:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Hour");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Minutes");

        jcbHours.setPreferredSize(new java.awt.Dimension(100, 22));

        jcbMinutes.setPreferredSize(new java.awt.Dimension(100, 22));

        jbtnUpdateNew.setText("Insert match");
        jbtnUpdateNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnGoBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jcbSeason, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtHost))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbGuest, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jbtnUpdateNew, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(16, 16, 16)
                                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(33, 33, 33)
                                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jcbHours, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jcbMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jcbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jcbMonth, 0, 101, Short.MAX_VALUE)
                                                .addGap(6, 6, 6))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(23, 23, 23)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcbDay, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(9, 9, 9)))))))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(welcomeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGoBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(welcomeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbSeason, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbDay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbHours, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jbtnUpdateNew, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBack1ActionPerformed
        ClubHomePage chp = new ClubHomePage(club);
        dispose();
    }//GEN-LAST:event_btnGoBack1ActionPerformed

    private void welcomeMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_welcomeMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_welcomeMessageActionPerformed

    private void jbtnUpdateNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateNewActionPerformed
        try {
            Season season = (Season) jcbSeason.getSelectedItem();
            Club guest = (Club) jcbGuest.getSelectedItem();
            LocalDateTime date = makeDate();
            if (date.isBefore(LocalDateTime.now())) {
                JOptionPane.showMessageDialog(rootPane, "Date can not be date before today", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                Match newMatch = new Match(club.getFullName() + " - " + guest.getFullName(), date, club.getIdKlub(), guest.getIdKlub(), season.getIdSezona());
                if (k.insertNewMatch(newMatch)) {
                    JOptionPane.showMessageDialog(rootPane, "New match inserted successfully", "Successfull", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Error", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Inputs error", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnUpdateNewActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoBack1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbtnUpdateNew;
    private javax.swing.JComboBox<Integer> jcbDay;
    private javax.swing.JComboBox<Club> jcbGuest;
    private javax.swing.JComboBox<Integer> jcbHours;
    private javax.swing.JComboBox<Integer> jcbMinutes;
    private javax.swing.JComboBox<String> jcbMonth;
    private javax.swing.JComboBox<Season> jcbSeason;
    private javax.swing.JComboBox<Integer> jcbYear;
    private javax.swing.JTextField txtHost;
    private javax.swing.JTextField welcomeMessage;
    // End of variables declaration//GEN-END:variables

    private void addListener() {

        jcbSeason.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Season selectedSeason = (Season) jcbSeason.getSelectedItem();
                String seasonName = selectedSeason.getName().substring(0, 4);
                //System.out.println(seasonName);
                int season = Integer.parseInt(seasonName);
                jcbYear.removeAllItems();
                jcbYear.addItem(season);
                jcbYear.addItem(season + 1);

            }

        });

        jcbYear.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Integer selectedYear = (Integer) jcbYear.getSelectedItem();
                //System.out.println(selectedYear);
                String selectedMonth = (String) jcbMonth.getSelectedItem();
                //System.out.println(selectedMonth);

                if (selectedYear != null && jcbYear.getSelectedIndex() == 0) {
                    jcbMonth.removeAllItems();
                    if (selectedYear == LocalDateTime.now().getYear()) {
                        int month = LocalDateTime.now().getMonthValue();
                        if (month == 9) {
                            jcbMonth.addItem("September");
                            jcbMonth.addItem("October");
                            jcbMonth.addItem("November");
                            jcbMonth.addItem("December");
                        } else if (month == 10) {
                            jcbMonth.addItem("October");
                            jcbMonth.addItem("November");
                            jcbMonth.addItem("December");
                        } else if (month == 11) {
                            jcbMonth.addItem("November");
                            jcbMonth.addItem("December");
                        } else if (month == 12) {
                            jcbMonth.addItem("December");
                        }
                    } else {
                        jcbMonth.addItem("September");
                        jcbMonth.addItem("October");
                        jcbMonth.addItem("November");
                        jcbMonth.addItem("December");
                    }
                } else if (selectedYear != null) {
                    jcbMonth.removeAllItems();
                    if (selectedYear == LocalDateTime.now().getYear()) {
                        int month = LocalDateTime.now().getMonthValue();
                        if (month == 1) {
                            jcbMonth.addItem("January");
                            jcbMonth.addItem("February");
                            jcbMonth.addItem("March");
                            jcbMonth.addItem("April");
                            jcbMonth.addItem("May");
                            jcbMonth.addItem("June");
                        } else if (month == 2) {
                            jcbMonth.addItem("February");
                            jcbMonth.addItem("March");
                            jcbMonth.addItem("April");
                            jcbMonth.addItem("May");
                            jcbMonth.addItem("June");
                        } else if (month == 3) {
                            jcbMonth.addItem("March");
                            jcbMonth.addItem("April");
                            jcbMonth.addItem("May");
                            jcbMonth.addItem("June");
                        } else if (month == 4) {
                            jcbMonth.addItem("April");
                            jcbMonth.addItem("May");
                            jcbMonth.addItem("June");
                        } else if (month == 5) {
                            jcbMonth.addItem("May");
                            jcbMonth.addItem("June");
                        } else if (month == 6) {
                            jcbMonth.addItem("June");
                        }
                    } else {
                        jcbMonth.addItem("January");
                        jcbMonth.addItem("February");
                        jcbMonth.addItem("March");
                        jcbMonth.addItem("April");
                        jcbMonth.addItem("May");
                        jcbMonth.addItem("June");
                    }
                }

                if (selectedMonth != null && selectedYear != null && selectedYear % 4 == 0 && selectedMonth.equals("February")) {
                    jcbDay.removeAllItems();
                    for (int i = 1; i <= 29; i++) {
                        jcbDay.addItem(i);
                    }
                } else if (selectedMonth != null && selectedYear != null && selectedYear % 4 != 0 && selectedMonth.equals("February")) {
                    jcbDay.removeAllItems();
                    for (int i = 1; i <= 28; i++) {
                        jcbDay.addItem(i);
                    }
                }
            }
        });

        jcbMonth.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                String selectedMonth = (String) jcbMonth.getSelectedItem();
                //System.out.println(selectedMonth);
                Integer selectedYear = (Integer) jcbYear.getSelectedItem();
                //System.out.println(selectedYear);
                if (selectedMonth != null && selectedYear != null && selectedYear % 4 == 0 && selectedMonth.equals("February")) {
                    jcbDay.removeAllItems();
                    if (selectedYear == LocalDateTime.now().getYear() && selectedMonth.equals(getMonthName(LocalDateTime.now().getMonthValue()))) {
                        int dayToday = LocalDateTime.now().getDayOfMonth();
                        for (int i = dayToday; i <= 29; i++) {
                            jcbDay.addItem(i);
                        }
                    } else {
                        for (int i = 1; i <= 29; i++) {
                            jcbDay.addItem(i);
                        }
                    }
                } else if (selectedMonth != null && selectedYear != null && selectedYear % 4 != 0 && selectedMonth.equals("February")) {
                    jcbDay.removeAllItems();
                    if (selectedYear == LocalDateTime.now().getYear() && selectedMonth.equals(getMonthName(LocalDateTime.now().getMonthValue()))) {
                        int dayToday = LocalDateTime.now().getDayOfMonth();
                        for (int i = dayToday; i <= 28; i++) {
                            jcbDay.addItem(i);
                        }
                    } else {
                        for (int i = 1; i <= 28; i++) {
                            jcbDay.addItem(i);
                        }
                    }
                } else if (selectedMonth != null && selectedYear != null && (selectedMonth.equals("April") || selectedMonth.equals("June") || selectedMonth.equals("September") || selectedMonth.equals("November"))) {
                    jcbDay.removeAllItems();
                    if (selectedYear == LocalDateTime.now().getYear() && selectedMonth.equals(getMonthName(LocalDateTime.now().getMonthValue()))) {
                        int dayToday = LocalDateTime.now().getDayOfMonth();
                        for (int i = dayToday; i <= 30; i++) {
                            jcbDay.addItem(i);
                        }
                    } else {
                        for (int i = 1; i <= 30; i++) {
                            jcbDay.addItem(i);
                        }
                    }
                } else {
                    jcbDay.removeAllItems();
                    if (selectedMonth != null && selectedYear == LocalDateTime.now().getYear() && selectedMonth.equals(getMonthName(LocalDateTime.now().getMonthValue()))) {
                        int dayToday = LocalDateTime.now().getDayOfMonth();
                        for (int i = dayToday; i <= 31; i++) {
                            jcbDay.addItem(i);
                        }
                    } else {
                        for (int i = 1; i <= 31; i++) {
                            jcbDay.addItem(i);
                        }
                    }
                }
            }

        });

        jcbDay.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jcbHours.removeAllItems();
                String selectedMonth = (String) jcbMonth.getSelectedItem();
                //System.out.println(selectedMonth);
                Integer selectedYear = (Integer) jcbYear.getSelectedItem();
                //System.out.println(selectedYear);
                Integer selectedDay = (Integer) jcbDay.getSelectedItem();
                int hourToday = LocalDateTime.now().getHour();
                if (selectedDay != null && selectedMonth != null && selectedYear != null && selectedYear == LocalDateTime.now().getYear()
                        && selectedMonth.equals(getMonthName(LocalDateTime.now().getMonthValue())) && selectedDay == LocalDateTime.now().getDayOfMonth()) {
                    if (LocalDateTime.now().getMinute() > 45) {
                        for (int i = hourToday + 1; i <= 22; i++) {
                            jcbHours.addItem(i);
                        }
                    } else {
                        for (int i = hourToday; i <= 22; i++) {
                            jcbHours.addItem(i);
                        }
                    }

                } else {
                    for (int i = 8; i <= 22; i++) {
                        jcbHours.addItem(i);
                    }
                }
            }

        });

        jcbHours.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jcbMinutes.removeAllItems();
                String selectedMonth = (String) jcbMonth.getSelectedItem();
                System.out.println(selectedMonth);
                Integer selectedYear = (Integer) jcbYear.getSelectedItem();
                System.out.println(selectedYear);
                Integer selectedDay = (Integer) jcbDay.getSelectedItem();
                Integer selectedHours = (Integer) jcbHours.getSelectedItem();

                int todayMinutes = LocalDateTime.now().getMinute();

                if (selectedHours != null && selectedDay != null && selectedMonth != null && selectedYear != null && selectedYear == LocalDateTime.now().getYear()
                        && selectedMonth.equals(getMonthName(LocalDateTime.now().getMonthValue())) && selectedDay == LocalDateTime.now().getDayOfMonth()
                        && selectedHours == LocalDateTime.now().getHour()) {
                    if (todayMinutes > 45) {
                        for (int i = LocalDateTime.now().getHour() + 1; i <= 22; i++) {
                            jcbHours.addItem(i);
                        }
                        for (int i = 0; i < minutes.length; i++) {
                            jcbMinutes.addItem(minutes[i]);
                        }
                    } else if (todayMinutes > 30) {
                        for (int i = 3; i < minutes.length; i++) {
                            jcbMinutes.addItem(minutes[i]);
                        }
                    } else if (todayMinutes > 15) {
                        for (int i = 2; i < minutes.length; i++) {
                            jcbMinutes.addItem(minutes[i]);
                        }
                    } else if (todayMinutes > 0) {
                        for (int i = 1; i < minutes.length; i++) {
                            jcbMinutes.addItem(minutes[i]);
                        }
                    }
                } else {
                    for (int i = 0; i < minutes.length; i++) {
                        jcbMinutes.addItem(minutes[i]);
                    }
                }

            }

        });
    }

    private LocalDateTime makeDate() {
        int year = (int) jcbYear.getSelectedItem();
        String monthStr = (String) jcbMonth.getSelectedItem();
        int day = (int) jcbDay.getSelectedItem();
        int hours = (int) jcbHours.getSelectedItem();
        int minutes = (int) jcbMinutes.getSelectedItem();
        int month = 1;
        switch (monthStr) {
            case "January":
                month = 1;
                break;
            case "February":
                month = 2;
                break;
            case "March":
                month = 3;
                break;
            case "April":
                month = 4;
                break;
            case "May":
                month = 5;
                break;
            case "June":
                month = 6;
                break;
            case "July":
                month = 7;
                break;
            case "August":
                month = 8;
                break;
            case "September":
                month = 9;
                break;
            case "October":
                month = 10;
                break;
            case "November":
                month = 11;
                break;
            case "December":
                month = 12;
                break;
            default:
                month = 1;
        }
        LocalDateTime date = LocalDateTime.of(year, month, day, hours, minutes);
        return date;
    }

    private String getMonthName(int index) {
        switch (index) {
            case 1:
                return "January";
            case 2:
                return "February";
            case 3:
                return "March";
            case 4:
                return "April";
            case 5:
                return "May";
            case 6:
                return "June";
            case 7:
                return "July";
            case 8:
                return "August";
            case 9:
                return "September";
            case 10:
                return "October";
            case 11:
                return "November";
            case 12:
                return "December";
            default:
                return "January";
        }
    }
}
